### ISSUE TITLE
feature: use pull request on for doc update instead of directly committing.

### ISSUE THREAD

**Issue by s1n7ax** [ellisonleao/nvim-plugin-template#9]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Why?

- Adding permission to create a pull request is easy
- Bot directly committing to main doesn't sound good
- It's better to review before merging

### Describe the solution you'd like

This is what I'm using to create a pull request to update the vimdoc

```yaml
on:
  push:
    branches:
      - main

name: docs

permissions:
  pull-requests: write
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: "<name>"
          dedupsubheadings: false
          version: "Neovim >= 0.9.4"
          demojify: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: "main"
```

### Describe alternatives you've considered

.
